### ISSUE TITLE
tagging each episode

### ISSUE THREAD

**Issue by erikyuzwa** [Limeoats/cavestory-development#1]
Hey man, 
as a suggestion maybe look into git tagging your repo as you continue to evolve the codebase for each episode. That way you can fetch the state of the repository for that particular episode.

If it's interrupting your workflow too much though, don't bother. Just a suggestion.

`git tag -a v0.1 -m 'episode 1'` 
`git push --tags origin`

**Comment by Limeoats** [comment]
Thank you for the suggestion. I did not know that was a possibility, but it will definitely help those watching my videos follow along better. I'll start doing that going forward.

**Comment by erikyuzwa** [comment]
:+1:

**Comment by Limeoats** [comment]
FYI - You can now view the source code after each episode by checking out the respective release.

**Comment by erikyuzwa** [comment]
that's awesome, thanks a lot.
